apiVersion: v1
kind: Namespace
metadata:
  name: fiapx
---
apiVersion: v1
kind: Secret
metadata:
  name: upload-service-secrets
  namespace: fiapx
type: Opaque
stringData:
  connection-string: "Host=postgres-upload-service;Port=5432;Database=fiapx_upload;Username=fiapx;Password=fiapx@2024"
  jwt-secret-key:    "fiapx-super-secret-key-at-least-32-chars-long!"
  minio-access-key:  "fiapx"
  minio-secret-key:  "fiapx@2024"
  rabbitmq-password: "fiapx@2024"
